version: '3.9'

services:
  auth_service:
    build: ./auth_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
    

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: femguard_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
